controllers:
    resource: ../src/Controller/
    type: attribute

app_logout:
    path: /logout
    methods: GET

api_borrar:
    path: /api/borrar/{id}
    controller: App\Controller\TareasController::borrar
    methods: GET

api_insertar:
    path: /api/insertar
    controller: App\Controller\TareasController::insertar
    methods: POST